"""Course system event types for event-driven architecture."""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict

from shared.core.course_models import CoursePreferences


class CourseRequestedEvent(BaseModel):
    """User requests a new course."""

    model_config = ConfigDict(frozen=True)

    type: Literal["course_requested"] = "course_requested"
    query: str
    time_hours: float
    preferences: Optional[CoursePreferences] = None


class EmbeddingGeneratedEvent(BaseModel):
    """Embedding has been generated for course query."""

    model_config = ConfigDict(frozen=True)

    type: Literal["embedding_generated"] = "embedding_generated"
    embedding: List[float]


class CorpusSearchCompletedEvent(BaseModel):
    """Corpus search has completed."""

    model_config = ConfigDict(frozen=True)

    type: Literal["corpus_search_completed"] = "corpus_search_completed"
    chunks: List[Dict[str, Any]]


class BookSummariesFoundEvent(BaseModel):
    """Relevant book summaries have been found."""

    model_config = ConfigDict(frozen=True)

    type: Literal["book_summaries_found"] = "book_summaries_found"
    books: List[Dict[str, Any]]  # List of {book_id, summary_json, similarity}


class OutlineGeneratedEvent(BaseModel):
    """Course outline has been generated by LLM (legacy - for single-phase)."""

    model_config = ConfigDict(frozen=True)

    type: Literal["outline_generated"] = "outline_generated"
    outline_json: str


class PartsGeneratedEvent(BaseModel):
    """Course parts structure has been generated (Phase 1)."""

    model_config = ConfigDict(frozen=True)

    type: Literal["parts_generated"] = "parts_generated"
    parts_text: str  # Text output from Phase 1


class PartSectionsGeneratedEvent(BaseModel):
    """Sections for a part have been generated (Phase 2-N)."""

    model_config = ConfigDict(frozen=True)

    type: Literal["part_sections_generated"] = "part_sections_generated"
    sections_text: str  # Text output for this part
    part_index: int  # Which part (0-based)


class AllPartsCompleteEvent(BaseModel):
    """All parts have been generated and outline is complete."""

    model_config = ConfigDict(frozen=True)

    type: Literal["all_parts_complete"] = "all_parts_complete"


class OutlineReviewEvent(BaseModel):
    """Outline review and adjustment completed (Phase N+1)."""

    model_config = ConfigDict(frozen=True)

    type: Literal["outline_review"] = "outline_review"
    reviewed_outline_text: str  # Adjusted outline text


class CourseStoredEvent(BaseModel):
    """Course has been stored in database."""

    model_config = ConfigDict(frozen=True)

    type: Literal["course_stored"] = "course_stored"
    course_id: str


class CourseEventError(BaseModel):
    """Error occurred during course creation."""

    model_config = ConfigDict(frozen=True)

    type: Literal["course_error"] = "course_error"
    error_message: str
    error_code: Optional[str] = None


# Union type for all course events
CourseEvent = Union[
    CourseRequestedEvent,
    EmbeddingGeneratedEvent,
    CorpusSearchCompletedEvent,
    BookSummariesFoundEvent,
    OutlineGeneratedEvent,  # Legacy
    PartsGeneratedEvent,  # Phase 1
    PartSectionsGeneratedEvent,  # Phase 2-N
    AllPartsCompleteEvent,  # All parts done
    OutlineReviewEvent,  # Phase N+1
    CourseStoredEvent,
    CourseEventError,
]

